version: '3.8'

services:
  backend:
    depends_on: 
        - "db"
    image: backend-image
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "7256:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AutomobileContext=Host=db;Port=5432;username=postgres;password=postgres;Database=AutomobileDB;Pooling=true; Include Error Detail = True
      - ASPNETCORE_URLS=http://+:80
  
  frontend:
    image: frontend-image
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@automobile.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
  
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AutomobileDB
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: