version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "7256:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    image: frontend-image
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"