namespace backend.Models.Shared
{
    public enum Company
    {
        TOYOTA,
        FORD,
        CHEVROLET,
        HONDA,
        VOLKSWAGEN,
        BMW,
        MERCEDES_BENZ,
        AUDI,
        NISSAN,
        HYUNDAI,
        KIA,
        MAZDA,
        SUBARU,
        JEEP,
        LEXUS,
        PORSCHE,
        TESLA,
        VOLVO,
        CADILLAC,
        LAND_ROVER,
        GMC,
        FIAT,
        CHRYSLER,
        JAGUAR,
        MITSUBISHI,
    }
}